### ISSUE TITLE
Define Metadata format for Rego policies

### ISSUE THREAD

**Issue by Blokje5** [policy-hub/policy-hub-cli#1]
In order to make policies searchable we need to have some form of metadata that maintains relevant search information. We can base this format on e.g. [ArtificatHub](https://artifacthub.io/packages/opa/deprek8ion/deprek8ion) or [Helm Hub](https://hub.helm.sh/charts/fyipe/Fyipe).

At the very minimum the following fields should be included:

- Maintainer(s)
- Version
- Homepage/Link
- Keywords
- Description

Ideally we also support an Icon & a Long README style description.

**Comment by xchapter7x** [comment]
To support this being used by some sort of CLI, and to maintain a testable versioned contract, im thinking about making this a package. im imagining, in time, some validation utility for people crafting these meta files for 3rd party policy stores.

this way it can be easily and consistently consumed in the form of a marshal/unmarshal interface. 
having these data models defined as structs better communicate the formatting as well IMHO. 

@Blokje5 any thoughts?
im going to frame up a first pass on this shortly.

**Comment by Blokje5** [comment]
It is indeed good to wrap this in a Package. Indeed we will run into versioning and translation issues in the future, so starting with a Package makes sense!
