### ISSUE TITLE
bundled registries file with CLI

### ISSUE THREAD

**Issue by xchapter7x** [policy-hub/policy-hub-cli#16]
when the CLI is used it should come with the a reference to the bundled registries yaml.

Thoughts on implementation:
- include a URL to the file, and use that to create a registries list file if one does not exist.

Intent:
As a user of the CLI, 
When i wish to search and install OPA policies
Then there should be at least one pre-loaded registry of known policy repos to search.

**Comment by Blokje5** [comment]
Sounds good. We could maybe add a config file where people can add registry locations to search. A bit like `/etc/apt/sources.list`.
